### PR TITLE
Fix #138 - Warning regression fix should always target stable should only be shown for PRs that close open issues

### LINKED ISSUE #138: Warning regression fix should always target stable should only be shown for PRs that close open issues
image

e.g. https://github.com/dlang/phobos/pull/5616#pullrequestreview-50208720

### PR DESCRIPTION
**Pull request by wilzbach**
See https://github.com/dlang-bots/dlang-bot/issues/138

### CODE REVIEW

File: test/comments.d [hunk 1]
```diff
@@ -220,7 +220,9 @@ unittest
 unittest
 {
     setAPIExpectations(
-        "/github/repos/dlang/phobos/pulls/4921/commits",
+        "/github/repos/dlang/phobos/pulls/4921/commits", (ref Json j) {
+            j[0]["commit"]["message"] = "Fix Issue 8573";
```
Comment (wilzbach) [inline test/comments.d]: The commit message was "Issue 8573 ..." so no stable warning would have been shown for this test.

File: test/comments.d [hunk 2]
```diff
@@ -232,7 +234,11 @@ unittest
 8573,"A simpler Phobos function that returns the index of the mix or max item","NEW","---","regression","P2"`);
         },
         "/github/orgs/dlang/public_members?per_page=100",
-        // no bug fix label, since Issues are only referenced but not fixed according to commit messages
+        "/github/repos/dlang/phobos/issues/4921/labels",
+        "/github/repos/dlang/phobos/issues/4921/labels",
```
Comment (wilzbach) [inline test/comments.d]: The bot tries to add a "Bug fix" label now, so unfortunately we have to be a bit explicit
