### PR TITLE
fix #167 - fix misleading error output during tests

### LINKED ISSUE #167: misleading error output during test
Doesn't find exception and reported failures.
https://travis-ci.org/dlang-bots/dlang-bot/jobs/328848474#L821
https://travis-ci.org/dlang-bots/dlang-bot/jobs/328848474#L1049
Or at least doesn't mark them as expected while silencing them.

Maybe we should look at unit-threaded for better output?

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

File: source/dlangbot/utils.d [hunk 1]
```diff
@@ -2,8 +2,74 @@ module dlangbot.utils;
...
+    version (unittest)
+    {
+        if (_expectedStatusCode == statusCode)
+        {
+            _expectedStatusCode = 0;
+            return true;
+        }
+    }
+    return false;
+}
```
Comment (wilzbach) [inline source/dlangbot/utils.d]: Hmm shouldn't the test logic be separated from the application logic?

Comment (MartinNowak) [reply source/dlangbot/utils.d]: Yes, if you have a better idea, go for it. Doesn't really fit the `runAsync`, `runTrello` pattern.
